id: ICEA1EBF7
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:27:40.357657
last_modified: 2023-02-08 15:27:40.357758
source_metadata:
  title: 'PP: Vajracchedikā Prajñāpāramitā'
  language: zh
bases:
  DAA0:
    base_file: DAA0.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
